In [21]:
import numpy as np


def CtoF(Ctemp):
    Ftemp = 9 / 5 * Ctemp + 32
    return Ftemp

In [22]:
# 1. 데이터 준비

data_C = np.array(range(0, 100))
data_F = CtoF(data_C)

X = data_C
y = data_F

In [23]:
# 2. 데이터 분할

from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.2, random_state=1)
train_X = train_X.reshape(-1, 1)
test_X = test_X.reshape(-1, 1)

In [24]:
# 3. 모델 준비

from sklearn.linear_model import LinearRegression

linear = LinearRegression()

In [25]:
# 4. 학습

linear.fit(train_X, train_y)

LinearRegression()

In [26]:
# 5. 예측 / 평가

predict = linear.predict(test_X)
test_X, predict

(array([[80],
        [84],
        [33],
        [81],
        [93],
        [17],
        [36],
        [82],
        [69],
        [65],
        [92],
        [39],
        [56],
        [52],
        [51],
        [32],
        [31],
        [44],
        [78],
        [10]]),
 array([176. , 183.2,  91.4, 177.8, 199.4,  62.6,  96.8, 179.6, 156.2,
        149. , 197.6, 102.2, 132.8, 125.6, 123.8,  89.6,  87.8, 111.2,
        172.4,  50. ]))

In [27]:
pred_f = linear.predict([[30]])
pred_f

array([86.])

In [28]:
acc = linear.score(test_X, test_y)
acc

1.0