In [2]:
import numpy as np

In [7]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [3]:
arr1 = np.array([1, 2, 3])
type(arr1), arr1.shape

(numpy.ndarray, (3,))

In [4]:
arr2 = np.array([[1, 2, 3],
                [2, 3, 4]])
type(arr2), arr2.shape

(numpy.ndarray, (2, 3))

In [5]:
arr3 = np.array([[1, 2, 3]])
type(arr3), arr3.shape

(numpy.ndarray, (1, 3))

In [6]:
arr1.ndim, arr2.ndim, arr3.ndim

(1, 2, 2)

In [8]:
lst1 = [1, 2, 3]
type(lst1)
arr1 = np.array(lst1)
type(arr1)
arr1,arr1.dtype

list

numpy.ndarray

(array([1, 2, 3]), dtype('int32'))

In [9]:
lst2 = [1, 2, 'test']
arr2 = np.array(lst2)
arr2, arr2.dtype

# int와 string이 섞여 있는 lst2를 ndarray로 변환한 arr2는 숫자형 값이 모두 문자열로 변환됨.
# ndarray는 데이터 값이 모두 같은 데이터 타입이어야 하므로 서로 다른 데이터 타입이 섞여 있을 경우 데이터 타입이 더 큰 데이터 타입으로 변환됨.

(array(['1', '2', 'test'], dtype='<U11'), dtype('<U11'))

In [10]:
lst3 = [1, 2, 3.0]
arr3 = np.array(lst3)
arr3, arr3.dtype

(array([1., 2., 3.]), dtype('float64'))

In [11]:
# astype

arr_int = np.array([1, 2, 3])
arr_float = arr_int.astype('float64')
arr_float, arr_float.dtype

(array([1., 2., 3.]), dtype('float64'))

In [12]:
arr_int2 = arr_float.astype('int32')
arr_int2, arr_int2.dtype

(array([1, 2, 3]), dtype('int32'))

In [13]:
arr_float2 = np.array([1.1, 2.1, 3.1])
arr_int3 = arr_float2.astype('int32')
arr_int3, arr_int3.dtype

(array([1, 2, 3]), dtype('int32'))

In [14]:
# ndarray를 편리하게 생성하기 - arange, zeros, ones

seq_arr = np.arange(10)
seq_arr, seq_arr.dtype, seq_arr.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'), (10,))

In [15]:
# np.zeros() : 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환

zero_arr = np.zeros((3, 2), dtype = 'int32')
zero_arr
zero_arr.dtype, zero_arr.shape

array([[0, 0],
       [0, 0],
       [0, 0]])

(dtype('int32'), (3, 2))

In [16]:
# np.ones() : 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray 반환

one_arr = np.ones((3, 2))
one_arr
one_arr.dtype, one_arr.shape

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

(dtype('float64'), (3, 2))

In [17]:
# reshape() : ndarray를 특정 차원 및 크기로 변환.

arr1 = np.arange(10)
arr1

arr2 = arr1.reshape(2, 5)
arr2

arr3 = arr1.reshape(5, 2)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
# reshape() 인자를 -1로 적용
# 원래 ndarray와 호환되는 새로운 shape로 변환해 줌.
# reshape(-1, 1) 자주 사용. 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 1개의 컬럼을 가진 ndarray로 변환됨을 보장.

arr2 = arr1.reshape(-1, 5)
arr2

arr3 = arr1.reshape(5, -1)
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
# argsort() 정렬 시 원본 행렬의 인덱스

name_arr = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_arr = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_arr)
sort_indices_asc
name_arr[sort_indices_asc]

array([0, 2, 4, 1, 3], dtype=int64)

array(['John', 'Sarah', 'Samuel', 'Mike', 'Kate'], dtype='<U6')

In [20]:
# 행렬 내적(행렬 곱)
# np.dot()

A = np.array([[1, 2, 3],
            [4, 5, 6]])

B = np.array([[7, 8],
            [9, 10],
            [11, 12]])

dot_product = np.dot(A, B)
dot_product

array([[ 58,  64],
       [139, 154]])

In [21]:
# 전치행렬
# np.transpose()

A = np.array([[1, 2],
            [3, 4]])

transpose_mat = np.transpose(A)
transpose_mat

array([[1, 3],
       [2, 4]])