In [2]:
import numpy as np

In [3]:
a = np.arange(5)

In [4]:
# 합과 산술평균
# sum(), mean()
a.sum(), a.mean() 

(10, 2.0)

In [5]:
# 표준편차와 분산
# std(), var()
a.std(), a.var()

(1.4142135623730951, 2.0)

In [6]:
# 최댓값, 최소값
# max(), min()
a.max(), a.min()

(4, 0)

In [7]:
a = np.arange(1, 5)

In [8]:
# 누적합, 누적곱 cumulative
# cumsum(), cumprod()
a.cumsum(), a.cumprod()

(array([ 1,  3,  6, 10], dtype=int32), array([ 1,  2,  6, 24], dtype=int32))

##### 행렬 연산
- 선형 대수를 위한 행렬 연산
- 행렬 곱, 전치 행렬, 역행렬, 행렬식 등
    - 행렬곱 : A.dot(B) or np.dot(A, B)
    - 전치행렬 : A.transpose() or np.transpose(A)
    - 역행렬 : np.linalg.inv(A)     linear algebra
    - 행렬식 : np.linalg.det(A)

In [9]:
a = np.arange(1, 5).reshape(2, 2)
a

array([[1, 2],
       [3, 4]])

In [10]:
b = np.array([3, 2, 0, 1]).reshape(2, 2)
b

array([[3, 2],
       [0, 1]])

In [14]:
# 행렬의 곱
np.dot(a, b), a.dot(b)

(array([[ 3,  4],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 9, 10]]))

In [15]:
np.dot(b, a), b.dot(a)

(array([[ 9, 14],
        [ 3,  4]]),
 array([[ 9, 14],
        [ 3,  4]]))

In [19]:
# 전치
b.transpose(), np.transpose(b), b.T

(array([[3, 0],
        [2, 1]]),
 array([[3, 0],
        [2, 1]]),
 array([[3, 0],
        [2, 1]]))

In [22]:
# 역행렬
np.linalg.inv(a), np.linalg.inv(b)

(array([[-2. ,  1. ],
        [ 1.5, -0.5]]),
 array([[ 0.33333333, -0.66666667],
        [ 0.        ,  1.        ]]))

In [23]:
# 행렬식
np.linalg.det(a), np.linalg.det(b)

(-2.0000000000000004, 3.0000000000000004)

In [27]:
a = np.arange(5,15)

In [28]:
# 1, 3, 4, 위치
a[[1, 3, 4]]

array([6, 8, 9])

In [31]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
# 3행 4열 정보
a[2, 3]     # 인덱스는 0부터

12

In [35]:
# 값 바꾸기
a[0, 0] = 100
a

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [36]:
# 2행 선택하기
a[1]

array([5, 6, 7, 8])

In [37]:
# 2열 선택하기
a[:,1]

array([ 2,  6, 10])

In [44]:
# 행 전체 변경
a[1] = [0, 0, 0, 0]         # OR np.array([0, 0, 0, 0])
a[2] = -3
a

array([[100,   2,   3,   4],
       [  0,   0,   0,   0],
       [ -3,  -3,  -3,  -3]])

In [48]:
# 2보다 큰 원소 선택
a > 2

array([[ True, False,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [49]:
# 비교연산 결과를 인덱스로 지정
a[a > 2]

array([100,   3,   4])

In [51]:
# 짝수인 원소 선택
a[a % 2 == 0]

array([100,   2,   4,   0,   0,   0,   0])

In [52]:
a[[0, 0], [2, 3]]       # 1행 3열, 1행 4열 원소

array([3, 4])

In [55]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
a[3:9]

array([4, 5, 6, 7, 8, 9])

In [57]:
# 배열명[start : end+1 : step]
# start에서 ed 범위까지의 자료 중 step 간격의 인덱스 지정
a[3:9:2]

array([4, 6, 8])

In [58]:
a[3::2]

array([ 4,  6,  8, 10])

In [59]:
a[::3]

array([ 1,  4,  7, 10])

In [60]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [64]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [67]:
a[0][:2], a[0,:2]

(array([1, 2]), array([1, 2]))

##### Array boolean 인덱싱
- 다차원의 인덱싱을 응용하여 boolean 인덱싱
- boolean 인덱싱을 통해 만들어낸 array를 통해 원하는 행 또는 열의 값만 뽑아냄
- 가리고 싶은 부분은 가리고, 원하는 요소만 꺼냄

In [68]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo',
                  'Park','Beomwoo'])
                  
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [69]:
# names 크기 확인
names.shape

(8,)

In [70]:
# 8행 4열의 실수 난수 배열 생성
# rand : uniformly
# randn : normally
data = np.random.randn(8, 4)
data

array([[-1.40188909, -0.815619  ,  1.18066036,  0.3217641 ],
       [ 0.25496521, -2.15482874, -0.62448626,  0.51259849],
       [-1.15367999,  0.02042133,  0.95205456,  1.82112228],
       [ 0.3818909 ,  0.59910807,  0.34099433,  0.0764816 ],
       [ 0.09419874,  0.11310337,  1.48054074,  0.87438809],
       [-0.76488143,  0.75093195,  1.35956624, -0.46413222],
       [-0.2942526 ,  0.88882347, -0.85306923,  0.48054223],
       [ 0.94521893,  0.58735894, -0.43691803,  1.2212803 ]])

In [71]:
data.shape

(8, 4)

In [74]:
# 요소가 Beomwoo인 항목에 대한 mask 생성
mask_Beomwoo = (names == 'Beomwoo')
mask_Beomwoo

array([ True,  True, False, False, False,  True, False,  True])

In [75]:
# 요소가 Beomwoo인 항목의 위치와 같은 행의 자료 가져오기
data[mask_Beomwoo, :]     # OR data[names_mask_Beomwoo]

array([[-1.40188909, -0.815619  ,  1.18066036,  0.3217641 ],
       [ 0.25496521, -2.15482874, -0.62448626,  0.51259849],
       [-0.76488143,  0.75093195,  1.35956624, -0.46413222],
       [ 0.94521893,  0.58735894, -0.43691803,  1.2212803 ]])

In [79]:
# 요소가 Kim인 행의 데이터만 꺼내기
data[names == 'Kim']    # OR data[names == 'Kim', :]

array([[-1.15367999,  0.02042133,  0.95205456,  1.82112228]])

In [86]:
# 논리 연산을 응용하여, 요소가 Kim 또는 Park인 행의 데이터만 꺼내기
data[(names == 'Kim') | (names == 'Park')]

array([[-1.15367999,  0.02042133,  0.95205456,  1.82112228],
       [-0.2942526 ,  0.88882347, -0.85306923,  0.48054223]])

In [95]:
data

array([[-1.40188909, -0.815619  ,  1.18066036,  0.3217641 ],
       [ 0.25496521, -2.15482874, -0.62448626,  0.51259849],
       [-1.15367999,  0.02042133,  0.95205456,  1.82112228],
       [ 0.3818909 ,  0.59910807,  0.34099433,  0.0764816 ],
       [ 0.09419874,  0.11310337,  1.48054074,  0.87438809],
       [-0.76488143,  0.75093195,  1.35956624, -0.46413222],
       [-0.2942526 ,  0.88882347, -0.85306923,  0.48054223],
       [ 0.94521893,  0.58735894, -0.43691803,  1.2212803 ]])

In [90]:
mask = data[:, 0] < 0
mask

array([ True, False,  True, False, False,  True,  True, False])

In [88]:
data[data[:,0] < 0][:, 2:4]
# data[data[:,0] < 0, 2:4]

array([[ 1.18066036,  0.3217641 ],
       [ 0.95205456,  1.82112228],
       [ 1.35956624, -0.46413222],
       [-0.85306923,  0.48054223]])

In [91]:
# 수학 관련 함수
# 각 성분의 절댓값 계산하기
np.abs(data)

array([[1.40188909, 0.815619  , 1.18066036, 0.3217641 ],
       [0.25496521, 2.15482874, 0.62448626, 0.51259849],
       [1.15367999, 0.02042133, 0.95205456, 1.82112228],
       [0.3818909 , 0.59910807, 0.34099433, 0.0764816 ],
       [0.09419874, 0.11310337, 1.48054074, 0.87438809],
       [0.76488143, 0.75093195, 1.35956624, 0.46413222],
       [0.2942526 , 0.88882347, 0.85306923, 0.48054223],
       [0.94521893, 0.58735894, 0.43691803, 1.2212803 ]])

In [97]:
# 제곱근
np.sqrt(abs(data)), np.abs(data) ** 0.5

(array([[1.18401397, 0.90311627, 1.08658196, 0.56724254],
        [0.5049408 , 1.46793349, 0.79024443, 0.71595984],
        [1.07409496, 0.14290324, 0.97573283, 1.34948964],
        [0.61797322, 0.77402072, 0.5839472 , 0.27655307],
        [0.30691813, 0.33630845, 1.21677473, 0.93508721],
        [0.874575  , 0.8665633 , 1.16600439, 0.6812725 ],
        [0.54245055, 0.94277435, 0.92361747, 0.69321153],
        [0.97222371, 0.76639347, 0.66099776, 1.10511551]]),
 array([[1.18401397, 0.90311627, 1.08658196, 0.56724254],
        [0.5049408 , 1.46793349, 0.79024443, 0.71595984],
        [1.07409496, 0.14290324, 0.97573283, 1.34948964],
        [0.61797322, 0.77402072, 0.5839472 , 0.27655307],
        [0.30691813, 0.33630845, 1.21677473, 0.93508721],
        [0.874575  , 0.8665633 , 1.16600439, 0.6812725 ],
        [0.54245055, 0.94277435, 0.92361747, 0.69321153],
        [0.97222371, 0.76639347, 0.66099776, 1.10511551]]))

In [98]:
# 제곱
np.square(data), data ** 2

(array([[1.96529303e+00, 6.65234352e-01, 1.39395889e+00, 1.03532139e-01],
        [6.50072602e-02, 4.64328688e+00, 3.89983087e-01, 2.62757207e-01],
        [1.33097752e+00, 4.17030910e-04, 9.06407891e-01, 3.31648637e+00],
        [1.45840660e-01, 3.58930479e-01, 1.16277131e-01, 5.84943506e-03],
        [8.87340217e-03, 1.27923730e-02, 2.19200088e+00, 7.64554525e-01],
        [5.85043609e-01, 5.63898796e-01, 1.84842036e+00, 2.15418722e-01],
        [8.65845920e-02, 7.90007157e-01, 7.27727105e-01, 2.30920835e-01],
        [8.93438835e-01, 3.44990528e-01, 1.90897368e-01, 1.49152557e+00]]),
 array([[1.96529303e+00, 6.65234352e-01, 1.39395889e+00, 1.03532139e-01],
        [6.50072602e-02, 4.64328688e+00, 3.89983087e-01, 2.62757207e-01],
        [1.33097752e+00, 4.17030910e-04, 9.06407891e-01, 3.31648637e+00],
        [1.45840660e-01, 3.58930479e-01, 1.16277131e-01, 5.84943506e-03],
        [8.87340217e-03, 1.27923730e-02, 2.19200088e+00, 7.64554525e-01],
        [5.85043609e-01, 5.63898796e

In [99]:
# 지수함수
# 각 성분을 자연대수 e의 지수로 삼은 값을 계산
# e^data
np.exp(data)

array([[0.24613156, 0.44236542, 3.25652398, 1.37955931],
       [1.29041673, 0.11592304, 0.53553649, 1.66962406],
       [0.31547369, 1.02063128, 2.59102762, 6.17878892],
       [1.46505224, 1.82049432, 1.40634526, 1.07948233],
       [1.09877809, 1.11974768, 4.39532176, 2.39740784],
       [0.46538911, 2.11897388, 3.89450365, 0.62868042],
       [0.74508826, 2.43226633, 0.42610511, 1.61695092],
       [2.57337672, 1.79923027, 0.64602438, 3.39152712]])

In [100]:
# 자연로그
np.log(abs(data))

array([[ 0.33782068, -0.20380795,  0.16607391, -1.1339366 ],
       [-1.36662816,  0.76771125, -0.47082595, -0.66826242],
       [ 0.14295683, -3.89117511, -0.04913293,  0.59945295],
       [-0.96262031, -0.51231328, -1.07588944, -2.5707051 ],
       [-2.3623485 , -2.17945307,  0.39240739, -0.13423097],
       [-0.26803444, -0.28644024,  0.30716571, -0.7675858 ],
       [-1.2233167 , -0.11785664, -0.15891458, -0.73284017],
       [-0.0563387 , -0.53211916, -0.82800967,  0.19989973]])

In [101]:
# 상용로그
np.log10(abs(data))

array([[ 0.14671366, -0.08851267,  0.07212498, -0.49246241],
       [-0.59351907,  0.33341276, -0.20447711, -0.29022268],
       [ 0.06208536, -1.68991588, -0.02133816,  0.26033911],
       [-0.41806069, -0.22249483, -0.46725285, -1.11644304],
       [-1.02595492, -0.94652444,  0.17042036, -0.05829577],
       [-0.11640588, -0.12439942,  0.13340037, -0.33335828],
       [-0.53127969, -0.05118449, -0.06901572, -0.31826844],
       [-0.02446759, -0.23109641, -0.35960003,  0.08681535]])

In [102]:
# 밑이 2
np.log2(abs(data))

array([[ 0.48737222, -0.29403271,  0.23959401, -1.63592471],
       [-1.97162767,  1.10757321, -0.67925827, -0.96409888],
       [ 0.2062431 , -5.61377903, -0.07088384,  0.8648278 ],
       [-1.38876755, -0.73911183, -1.55218036, -3.70874349],
       [-3.40814846, -3.14428614,  0.56612419, -0.19365435],
       [-0.38669196, -0.41324592,  0.44314644, -1.10739223],
       [-1.76487294, -0.17003119, -0.22926527, -1.05726487],
       [-0.08127956, -0.76768567, -1.19456544,  0.28839435]])

In [105]:
# 각 성분 부호 -> -1 or 0 or 1 반환
np.sign(data)

array([[-1., -1.,  1.,  1.],
       [ 1., -1., -1.,  1.],
       [-1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [-1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1.]])

In [110]:
data

array([[-1.40188909, -0.815619  ,  1.18066036,  0.3217641 ],
       [ 0.25496521, -2.15482874, -0.62448626,  0.51259849],
       [-1.15367999,  0.02042133,  0.95205456,  1.82112228],
       [ 0.3818909 ,  0.59910807,  0.34099433,  0.0764816 ],
       [ 0.09419874,  0.11310337,  1.48054074,  0.87438809],
       [-0.76488143,  0.75093195,  1.35956624, -0.46413222],
       [-0.2942526 ,  0.88882347, -0.85306923,  0.48054223],
       [ 0.94521893,  0.58735894, -0.43691803,  1.2212803 ]])

In [108]:
# 각 성분 소수 첫 번째 자리에서 내림한 값
np.floor(data)

array([[-2., -1.,  1.,  0.],
       [ 0., -3., -1.,  0.],
       [-2.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [-1.,  0.,  1., -1.],
       [-1.,  0., -1.,  0.],
       [ 0.,  0., -1.,  1.]])

In [109]:
# 올림값
np.ceil(data)

array([[-1., -0.,  2.,  1.],
       [ 1., -2., -0.,  1.],
       [-1.,  1.,  1.,  2.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  2.,  1.],
       [-0.,  1.,  2., -0.],
       [-0.,  1., -0.,  1.],
       [ 1.,  1., -0.,  2.]])

In [111]:
# NaN 여부 확인
np.isnan(np.sqrt(data))

C:\Users\JngMK\AppData\Local\Temp/ipykernel_12984/632016115.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.isnan(np.sqrt(data))


array([[ True,  True, False, False],
       [False,  True,  True, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False,  True],
       [ True, False,  True, False],
       [False, False,  True, False]])

In [113]:
# 무한대 확인
np.isinf(data)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [115]:
# sin
np.sin(data)

array([[-0.98576905, -0.72815001,  0.92485736,  0.31624062],
       [ 0.25221175, -0.834246  , -0.58468057,  0.49044341],
       [-0.91426099,  0.02041992,  0.81460889,  0.96883173],
       [ 0.37267582,  0.56390611,  0.33442433,  0.07640706],
       [ 0.09405949,  0.11286238,  0.99592973,  0.76715112],
       [-0.69245146,  0.68232036,  0.97777375, -0.447647  ],
       [-0.29002465,  0.77633069, -0.7533025 ,  0.46226006],
       [ 0.81062515,  0.55416452, -0.42314903,  0.93953856]])

In [117]:
# 전체 성분 합
np.sum(data)

6.29425764957678

In [119]:
# 우측
np.sum(data, axis = 1)

array([-0.71508363, -2.01175129,  1.63991819,  1.3984749 ,  2.56223094,
        0.88148453,  0.22204387,  2.31694014])

In [121]:
# 아래로
np.sum(data, axis = 0)

array([-1.93842933, -0.01070059,  3.39934271,  4.84404486])

In [122]:
np.mean(data)

0.19669555154927437

In [123]:
np.mean(data, axis=1)

array([-0.17877091, -0.50293782,  0.40997955,  0.34961872,  0.64055773,
        0.22037113,  0.05551097,  0.57923504])

In [125]:
np.std(data), np.std(data, axis=1)

(0.8905630510756297,
 array([1.00002278, 1.04274261, 1.10475743, 0.185718  , 0.57813587,
        0.86869554, 0.67507663, 0.62825142]))

In [126]:
np.min(data, axis = 0)

array([-1.40188909, -2.15482874, -0.85306923, -0.46413222])

In [128]:
# 최대값, 최소값 위치 인덱스
np.argmax(data), np.argmin(data)

(11, 5)

In [136]:
np.argmax(data, axis = 1)

array([2, 3, 3, 1, 2, 2, 1, 3], dtype=int64)

In [139]:
# 행마다 오름차순
np.sort(data)

array([[-1.40188909, -0.815619  ,  0.3217641 ,  1.18066036],
       [-2.15482874, -0.62448626,  0.25496521,  0.51259849],
       [-1.15367999,  0.02042133,  0.95205456,  1.82112228],
       [ 0.0764816 ,  0.34099433,  0.3818909 ,  0.59910807],
       [ 0.09419874,  0.11310337,  0.87438809,  1.48054074],
       [-0.76488143, -0.46413222,  0.75093195,  1.35956624],
       [-0.85306923, -0.2942526 ,  0.48054223,  0.88882347],
       [-0.43691803,  0.58735894,  0.94521893,  1.2212803 ]])

In [144]:
# 열마다 오름차순
np.sort(data, axis=0)

array([[-1.40188909, -2.15482874, -0.85306923, -0.46413222],
       [-1.15367999, -0.815619  , -0.62448626,  0.0764816 ],
       [-0.76488143,  0.02042133, -0.43691803,  0.3217641 ],
       [-0.2942526 ,  0.11310337,  0.34099433,  0.48054223],
       [ 0.09419874,  0.58735894,  0.95205456,  0.51259849],
       [ 0.25496521,  0.59910807,  1.18066036,  0.87438809],
       [ 0.3818909 ,  0.75093195,  1.35956624,  1.2212803 ],
       [ 0.94521893,  0.88882347,  1.48054074,  1.82112228]])

In [147]:
data = np.random.randn(3,3)
data

array([[ 0.14213949,  0.96828522,  0.94450209],
       [ 0.35204159,  1.69576256,  1.18400881],
       [ 1.37112503, -0.84413717,  0.61625061]])

In [150]:
np.sort(data)[::-1]

array([[-0.84413717,  0.61625061,  1.37112503],
       [ 0.35204159,  1.18400881,  1.69576256],
       [ 0.14213949,  0.94450209,  0.96828522]])

In [156]:
a = np.random.randn(2, 2)
b = np.random.randn(2, 2)
a , b

(array([[-1.51044709, -0.34656128],
        [ 0.66281747,  0.82115479]]),
 array([[ 1.56245249,  0.61153757],
        [-0.59674766, -0.95137621]]))

In [158]:
np.add(a, b)

array([[ 0.05200539,  0.2649763 ],
       [ 0.06606981, -0.13022142]])

In [159]:
np.subtract(a, b)

array([[-3.07289958, -0.95809885],
       [ 1.25956513,  1.772531  ]])

In [160]:
np.multiply(a, b)


array([[-2.36000182, -0.21193524],
       [-0.39553477, -0.78122713]])

In [161]:
np.divide(a, b)

array([[-0.96671554, -0.5667048 ],
       [-1.1107165 , -0.86312311]])

In [162]:
np.maximum(a, b)

array([[1.56245249, 0.61153757],
       [0.66281747, 0.82115479]])

In [163]:
np.minimum(a, b)

array([[-1.51044709, -0.34656128],
       [-0.59674766, -0.95137621]])