In [1]:
import numpy as np
 

np.__version__

'1.20.3'

In [2]:
data1 = [1, 2, 3]
data1

[1, 2, 3]

In [3]:
# 리스트 객체를 이용하여 array 생성
arr1 = np.array(data1)

In [4]:
# array 크기 확인
# array.shape -> tuple
arr1.shape

(3,)

In [5]:
# 리스트를 직접 입력하여 array 생성
arr2 = np.array([1, 2, 3, 4, 5])
arr2

array([1, 2, 3, 4, 5])

In [6]:
arr2.shape

(5,)

In [7]:
# array 자료형 확인
arr2.dtype

dtype('int32')

In [8]:
arr3 = np.array([1, 2, 3, 3.5, 4])
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [9]:
arr3.shape, arr3.dtype

((5,), dtype('float64'))

In [10]:
arr4 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr4.shape, arr4.dtype

((3, 3), dtype('int32'))

### Numpy 자료형
- 부호가 있는 정수 int(8, 16, 32, 64)
- 부호가 없는 정수 uint(8, 16, 32, 64)
- 실수 float(16, 32, 64, 128)
- 복소수 complex(64, 128, 256)
- 불리언 bool
- 문자열 string_
- 파이썬 오브젝트 object
- 유니코드 unicode_

In [12]:
# 범위를 지정해 배열 생성
# np.arange()
# np.arange([start,] stop [,step])
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [14]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [15]:
# reshape()
# 원소의 개수와 reshape 모든 인수의 곱이 같아야함
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
np.arange(12).reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [17]:
# 범위를 지정해 배열생성
# np.linsapce(start, stop [,num=50])
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
np.linspace(1, np.pi, 20)

array([1.        , 1.1127154 , 1.22543081, 1.33814621, 1.45086161,
       1.56357701, 1.67629242, 1.78900782, 1.90172322, 2.01443863,
       2.12715403, 2.23986943, 2.35258483, 2.46530024, 2.57801564,
       2.69073104, 2.80344645, 2.91616185, 3.02887725, 3.14159265])

In [19]:
# 특별한 형태의 배열 생성
# np.zeros(shape, dtype=float, ...)
# 모든 요소가 0인 배열 생성
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.zeros((3,5)).reshape(5,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# 모든 요소가 1인 배열 생성
# np.ones(shpae, dtype=None)
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.ones((3, 5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
# 대각요소가 1인 배열 생성 1
# np.eye(n, m, k = K, dtype = 자료형)
# 3행 3열의 대각요소가 1인 행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(3, 4, k = 1, dtype = int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [26]:
# 대각요소가 1인 배열 생성 2
# np.identity(n, dtype = 자료형)
# n * n 크기의 단위행렬 생성
np.identity(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [27]:
# 초기화되지 않은 배열 생성
# np.empty(shape, dtype = float)
# 초기화되지 않은 배열 생성
np.empty(4)

array([1.03006364e-311, 6.23038336e-307, 1.60218491e-306, 1.37961302e-306])

In [28]:
# np.asarray
# 입력 데이터를 ndarray로 변환하거나 ndarray일 경우 새로 메모리에 ndarray가 생성되지 않음

In [29]:
# 배열의 데이터 타입 변환(형변환)
# astype(dtype)
# dtype : int, float, str
arr1 = np.array(['1.5', '0.62', '2', '3.14', '3.141592'])
arr1

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [30]:
arr1 = arr1.astype(float)
arr1, arr1.dtype

(array([1.5     , 0.62    , 2.      , 3.14    , 3.141592]), dtype('float64'))

In [31]:
arr2 = arr1.astype('float32')
arr2

array([1.5     , 0.62    , 2.      , 3.14    , 3.141592], dtype=float32)

In [32]:
arr1 = np.array(['1', '3', '5', '7', '9'])
arr1

array(['1', '3', '5', '7', '9'], dtype='<U1')

In [33]:
arr2 = arr1.astype(int)
arr2, arr2.dtype

(array([1, 3, 5, 7, 9]), dtype('int32'))

In [34]:
arr3 = arr1.astype(float)
arr3, arr3.dtype

(array([1., 3., 5., 7., 9.]), dtype('float64'))

In [35]:
# 실수형 배열을 정수형 배열로 변환
arr1 = np.array([10, 21, 0.549, 4.75, 5.98])
arr1, arr1.dtype

(array([10.   , 21.   ,  0.549,  4.75 ,  5.98 ]), dtype('float64'))

In [36]:
# 반올림
np.around(arr1, 2)

array([10.  , 21.  ,  0.55,  4.75,  5.98])

In [37]:
# 소숫점 아래 생략
arr2 = arr1.astype(int)
arr2, arr2.dtype

(array([10, 21,  0,  4,  5]), dtype('int32'))

In [38]:
# 숫자형 배열을 문자열 배열로 변환
arr1.astype('U')    # 유니코드

array(['10.0', '21.0', '0.549', '4.75', '5.98'], dtype='<U32')

In [39]:
arr1.astype('S')    # 바이트 문자열

array([b'10.0', b'21.0', b'0.549', b'4.75', b'5.98'], dtype='|S32')

In [40]:
# 난수 배열 생성
# random.rand()
np.random.rand(10)      # 1차원

array([0.14542714, 0.37142718, 0.16327874, 0.86593315, 0.06931522,
       0.56091173, 0.54880401, 0.75858331, 0.85644589, 0.92829864])

In [41]:
np.random.rand(2,5)     # 2차원

array([[0.59688412, 0.5104401 , 0.81000126, 0.9624414 , 0.70997208],
       [0.75031942, 0.00340995, 0.04782376, 0.29134693, 0.84190863]])

In [42]:
np.random.rand()

0.42550474597180377

In [43]:
# np.random.randint( [low,] high-1 [,size] )
np.random.randint(10)

7

In [44]:
np.random.randint(10, 50, (2, 3, 3))

array([[[12, 29, 26],
        [19, 42, 11],
        [15, 33, 23]],

       [[36, 27, 15],
        [39, 41, 47],
        [36, 35, 11]]])

In [45]:
# Array 연산
# 기본 연산(합, 차, 곱, 나눗셈 등)
# 기본적으로 동일한 크기의 array 간 연산 수행
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(10, 16).reshape(2, 3)

In [46]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [47]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [48]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [49]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [50]:
arr2 * 2

array([[20, 22, 24],
       [26, 28, 30]])

In [51]:
arr2 > 12

array([[False, False, False],
       [ True,  True,  True]])

In [52]:
# 배열의 Broadcasting
# 서로 크기가 다른 array들의 연산이 가능하도록 배열을 자동적으로 변환하여 연산 수행
arr3 = np.array([10,11,12])
arr1, arr3

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([10, 11, 12]))

In [53]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [54]:
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)